week1 hw1~6 done
Lidemy/mentor-program-2nd-twgd pull request #1
Opened 2018-09-03 15:19 UTC by twgd

小小問題：`hw5.js` 檔案中，`function join(str, concatStr) {}`原本標示的參數是不是誤把 `arr` 寫成  `str`？

因為是放入 array，我是不是可以改成 `arr` 比較符合讓人容易理解的原則？
``` javascript
function join(arr, concatStr) {}
```

2018-09-03 15:44 UTC, aszx87410 commented
是，改成 arr 比較符合語意，這邊忘記改到XD

2018-09-03 15:45 UTC, aszx87410 commented on homeworks/week1/hw1.js
> +  return star;
這一題題目說明是要「印出」星星喔，不是回傳

2018-09-03 15:46 UTC, aszx87410 commented on homeworks/week1/hw4.js
> +  return output;
同第一題，是要「印出」而非回傳
另外，想問一下為什麼特地把 1 放在外面而不是在迴圈裡讓 i = 1

2018-09-03 15:48 UTC, aszx87410 requested changes
大部分都 ok，把回傳的部分改成 console.log 就行了

2018-09-04 03:03 UTC, twgd commented on homeworks/week1/hw1.js
> +  return star;
原來如此！其實寫作業時根本沒有意識到題目寫的「印出」與「回傳」的差別XD
我再去仔細了解 console.log() 及 return。

2018-09-04 03:20 UTC, twgd commented on homeworks/week1/hw4.js
> +  return output;
因為 1 是任意整數的因數，寫題目時很直覺地認為一定會 output 1 ，想說直接從 2 開始跑就可以了XD

2018-09-04 08:19 UTC, twgd commented
@aszx87410 我 update 了 hw1 跟 hw4 囉～

想確認一下觀念：

「Unit Test 測試檔的 `expect()` 只對 `return` 的值有效。所以在需要用到 Unit Test 的時候，要 `return` 值出去。」我上面的理解應該正確吧？

覺得把第一期 week1 拆成第二期的 week1 及 week2 好明智，完全抓出我對「印出」及「回傳」這兩個題目需求的盲點XD 

因為第一期 week1 作業、寫 codewars 題目，都是要 `return` 值做測試，看到題目就猛 `return` XD，這次的作業有讓我仔細理解用法：

- `console.log()`：列出值，通常是給自己測試或 debug 時用的。
- `return`：跳出 `function`，回傳值。

2018-09-04 14:28 UTC, aszx87410 approved these changes

2018-09-04 14:28 UTC, aszx87410 commented
@twgd 是的，這個解釋給你 💯 ，恭喜完成作業一！

2018-09-04 14:29 UTC, merged